version: "3"
#app->我們自己產生的image(印象檔)
services:
  app:
    build: 
      context: 
    ports:
      - "80:80"
    volumes:
      - ./app:/code/app
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresal/data

volumes:
  postgres_data: